// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ZLE2yNqqdAMPKV8ei8m-pgzSViV710c',
    appId: '1:426236209221:android:84aff6d2cc9a61a7b75b2c',
    messagingSenderId: '426236209221',
    projectId: 'flutter-with-firebase-c95fe',
    storageBucket: 'flutter-with-firebase-c95fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1EUwCPH5V2TkgCdIwJcewP_VMXOBhVo',
    appId: '1:426236209221:ios:a5d5c28dc8e5b2d6b75b2c',
    messagingSenderId: '426236209221',
    projectId: 'flutter-with-firebase-c95fe',
    storageBucket: 'flutter-with-firebase-c95fe.appspot.com',
    androidClientId: '426236209221-8p52lnji2a0eh48rc02s46aujc2vg5ch.apps.googleusercontent.com',
    iosClientId: '426236209221-c85fnkji2769ig5b6j3bur249d8q2svn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

}